image: maven:3.8.6-openjdk-18

stages:
  - validate
  - compile
  - build

validate:
  stage: validate
  except:
    - tags
  script:
    - 'mvn validate'

compile:
  stage: compile
  except:
    - tags
  script:
    - 'mvn compile'
  cache:
    paths:
      - ./target

build:
  stage: build
  except:
    - tags
  script:
    - 'mvn package'
  artifacts:
    paths:
      - target/*.jar
  cache:
    policy: pull
    paths:
      - ./target