image: maven:3.8.3-openjdk-17

stages:
  - validate
  - compile
  - build

validate:
  stage: validate
  only:
    - dev
    - merge_requests
  except:
    - tags
  script:
    - 'mvn validate'

compile:
  stage: compile
  only:
    - dev
    - merge_requests
  except:
    - tags
  script:
    - 'mvn compile'
  cache:
    paths:
      - ./target

build:
  stage: build
  only:
    - dev
    - merge_requests
  except:
    - tags
  script:
    - 'mvn package'
  artifacts:
    paths:
      - target/*.jar
  cache:
    policy: pull
    paths:
      - ./target