stages:
  - test
  - build

.docker_login: &docker_login
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: '-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository'

Test:
  stage: test
  script:
    - ./mvnw test

Build jar:
  stage: build
  script:
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

Build an image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - *docker_login
    - APP_NAME=mvn help:evaluate -Dexpression=project.version -q -DforceStdout
    - APP_VERSION=mvn help:evaluate -Dexpression=project.version -q -DforceStdout
    - cd target
    - java -jar -Djarmode=layertools "${APP_NAME}"-"${APP_VERSION}".jar extract
    - if [ $CI_COMMIT_TAG == '' ]; then APP_VERSION=${CI_COMMIT_SHORT_SHA} fi
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/target"
      --dockerfile "${CI_PROJECT_DIR}/delivery/docker/Dockerfile"
      --build-arg "JAR_FOLDER=${CI_PROJECT_DIR}/target"
      --destination "${CI_REGISTRY_IMAGE}:${APP_VERSION}"