server:
  port: 8080

application:
  auth:
    cookie:
      name: authToken
      maxAgeInDays: 365

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
