server:
  port: 8080

application:
  auth:
    cookie:
      name: authToken
      maxAgeInDays: 365

spring.datasource.url: jdbc:postgresql://ip/whattimeprod
spring.datasource.username: user
spring.datasource.password: password
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update


management:
  endpoint:
    health:
      probes:
        enabled: true
    httptrace:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true