spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whattime
    username: whattime
    password: 10oclock
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true